console.log("Rodando o sistema de gerenciamento de dados")
console.log("Aplicação está se conectando ao banco de dados")
console.log("Enviando para o GitHub")
console.log("Enviado para o GitHub")
console.log("criando a página de contato")
